# This yaml file is used by Google Cloud Container Builder to build the
# microservices in parallel and push them to Google Container Registry.
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-f=Dockerfile.web',
          '-t=gcr.io/$PROJECT_ID/web:${REVISION_ID}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-f=Dockerfile.userdirectory',
          '-t=gcr.io/$PROJECT_ID/userdirectory:${REVISION_ID}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-f=Dockerfile.coffeedirectory',
          '-t=gcr.io/$PROJECT_ID/coffeedirectory:${REVISION_ID}', '.']
images:
  - 'gcr.io/$PROJECT_ID/web:${REVISION_ID}'
  - 'gcr.io/$PROJECT_ID/userdirectory:${REVISION_ID}'
  - 'gcr.io/$PROJECT_ID/coffeedirectory:${REVISION_ID}'
