# This yaml file is used by Google Cloud Container Builder to build the
# microservices in parallel and push them to Google Container Registry.

steps:
- name: gcr.io/ahmetb-public/skaffold
  args: ['run', '-f=skaffold-coffeedirectory.yaml', '-v=warning']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=coffee'

- name: gcr.io/ahmetb-public/skaffold
  args: ['run', '-f=skaffold-userdirectory.yaml', '-v=warning']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=coffee'

- name: gcr.io/ahmetb-public/skaffold
  args: ['run', '-f=skaffold-web.yaml', '-v=warning']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=coffee'
