apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy: gitCommit
  artifacts:
  - imageName: gcr.io/ahmetb-starter/userdirectory
    workspace: .
    dockerfilePath: Dockerfile.userdirectory
  local: {}
deploy:
  kubectl:
    manifests:
    - paths:
      - ./misc/kube/common/**
      - ./misc/kube/userdirectory/**
      parameters:
        USERDIRECTORY_IMAGE_REF: gcr.io/ahmetb-starter/userdirectory
