apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-http
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "coffee"
spec:
  backend:
    serviceName: web-local
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-local
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    nodePort: 32000
    port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: userdirectory
spec:
  type: ClusterIP
  selector:
    app: userdirectory
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: coffeedirectory
spec:
  type: ClusterIP
  selector:
    app: coffeedirectory
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002
